---
  - name: Installation Nginx
    become: yes
    apt: name=nginx state=latest

  - name: Start
    become: yes
    service: name=nginx state=started enabled=true

  - name: Supprimer le default.conf
    become: yes
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify: nginx reload
  
  - name: PHP
    become: yes
    include_tasks: php.yml

  - name: Configuration des sites
    become: yes
    include_tasks: site.yml
    with_items: "{{ domains }}"