---
- name: Creation du dossier
  become: yes
  file: path=/home/{{ user }}/{{ item.domain }} state=directory owner="{{ user }}"

- name: Clonnage du site {{ item.domain }} depuis {{ item.repo }}
  become: yes
  when: item.repo is defined
  git: dest=/home/{{ user }}/{{ item.domain }} clone=yes repo={{ item.repo }} remote=origin/{{ item.branch }} force=yes

- name: Lien vers www
  become: yes
  file: src=/home/{{ user }}/{{ item.domain }} dest=/var/www/{{ item.domain }} state=link

- name: Création de la configuration nginx
  become: yes
  template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ item.domain }} force=yes
  notify: nginx reload

- name: Activation du domain {{ item.domain }}
  become: yes
  file: src=/etc/nginx/sites-available/{{ item.domain }} dest=/etc/nginx/sites-enabled/{{ item.domain }} state=link
  notify: nginx reload

- name: Change le propriètaire
  become: yes
  file: path=/home/{{ user }}/{{ item.domain }} recurse=yes owner="{{ user }}" group="{{ user }}"

- stat: path=/home/{{ user }}/{{ item.domain }}/composer.lock
  register: composer_file

- name: Composer Install
  become: yes
  when: composer_file.stat.exists == false
  command: chdir=/home/{{ user }}/{{ item.domain }}/ composer install

- name: Composer Update
  become: yes
  when: composer_file.stat.exists == true
  command: chdir=/home/{{ user }}/{{ item.domain }}/ composer update

- name: test
  include_role:
    name: laravel
  with_items: 
    - "{{ domains }}"


...