---
- name : Installation du serveur seecretspot
  hosts: web
  #remote_user: hellodebian
  vars:
    user: cess
    domains:
      - domain: seecretspot.ovh
        php: yes
        repo: https://github.com/iamarnaud/repausecafe.git
        branch: master


  roles:
    - pack-base
    - user
    - cerbot
    - mysql
    - nginx

- name : Installation du serveur rebloch
  hosts: web2
  #remote_user: hellodebian
  vars:
    user: riko
    domains:
      - domain: rebloch.pw
        php: yes
        repo: https://github.com/Riko-L/projet_rebloch.git
        branch: master

  roles:
    - pack-base
    - user
    - cerbot
    - mysql
    - nginx
...