---
- name : Installation du serveur seecretspot
  hosts: web
  vars:
    user: cess
    domains:
      - domain: demo50.rebloch.pw #seecretspot.ovh
        php: yes
        repo: https://github.com/iamarnaud/repausecafe.git
        branch: master

  roles:
    - pack-base
    - user
    - cerbot
    - mysql
    - nginx


- name : Installation du serveur rebloch
  hosts: web2
  vars:
    user: riko
    domains:
      - domain: demo60.rebloch.pw #rebloch.pw
        php: yes
        repo: https://github.com/Riko-L/projet_rebloch.git
        branch: master

  roles:
    - pack-base
    - user
    - cerbot
    - mysql
    - nginx
...