---
  php_packages:
    - php7.2
    - php7.2-cli
    - php7.2-intl
    - php7.2-curl
    - php7.2-cgi
    - php7.2-fpm
    - php7.2-mysql
    - php7.2-gd
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-common
  php_timezone: Europe/Paris
  php_upload_max_filesize: "20M"
  php_post_max_size: "20M"
  php_memory_limit: "1024M"