- name: Ajout de la clef du dépots MYSQL
  become: yes
  apt_key: url=https://repo.mysql.com/RPM-GPG-KEY-mysql

- name: Ajout MYSQL aux dépots
  become: yes
  apt_repository: repo='{{ item }}'
  with_items:
    - deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7
    - deb-src http://repo.mysql.com/apt/debian/ stretch mysql-5.7

- name: APT update
  become: yes
  apt: update_cache=yes

- name: Installation MYSQL
  become: yes
  apt: name=mysql-server state=latest


- name: Start MYSQL
  become: yes
  service: name=mysql state=started enabled=true
