---
- name: Installation packages de base
  become : yes  
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - aptitude
    - python-mysqldb
    - vim
    - git
    - htop
    - git
    - zsh
    - zip
    - unzip
    - apt-transport-https
    - lsb-release
    - ca-certificates

- name: Mise à jours du serveur
  become: yes
  apt: update_cache=yes upgrade=yes
...